apiVersion: v1
kind: Service
metadata:
  name: aws-example-octodex
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: aws-example-octodex-service
  selector:
    app: aws-example-octodex
